# Generated by Django 2.0.7 on 2020-01-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_hist_passenger_hist_ride_hist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger_hist',
            name='assigned',
        ),
    ]
