# Generated by Django 2.0.7 on 2020-01-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_remove_passenger_hist_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_hist',
            name='assigned',
        ),
    ]
