# Generated by Django 2.0.7 on 2020-01-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_remove_driver_hist_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride_hist',
            name='driver_ride_id',
        ),
        migrations.RemoveField(
            model_name='ride_hist',
            name='passenger_ride_id',
        ),
    ]
