# Generated by Django 2.0.7 on 2020-01-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_auto_20200106_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='car_model',
            field=models.TextField(default='car'),
        ),
        migrations.AddField(
            model_name='ride_hist',
            name='car_model',
            field=models.TextField(default='car'),
        ),
    ]
