# Generated by Django 2.0.7 on 2020-01-12 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_auto_20200110_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('message', models.TextField()),
                ('driver_ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver')),
                ('ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.Ride')),
            ],
        ),
    ]
