# Generated by Django 2.0.7 on 2020-01-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_modified',
            field=models.DateTimeField(blank=True),
        ),
    ]
