# Generated by Django 2.0.7 on 2020-01-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_remove_message_ride_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
