# Generated by Django 2.0.7 on 2020-01-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0010_auto_20200112_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='stops',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='stops_arr',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
