# Generated by Django 2.0.7 on 2020-01-24 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers', '0012_auto_20200123_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_hist',
            name='username',
        ),
        migrations.AddField(
            model_name='driver_hist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
