# Generated by Django 2.0.7 on 2020-01-24 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers', '0013_auto_20200124_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger_hist',
            name='username',
        ),
        migrations.AddField(
            model_name='passenger_hist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
